# Generated by Django 5.0.6 on 2024-08-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messeneger', '0002_alter_message_options_remove_message_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='messege',
        ),
    ]
